# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_post_last'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='first',
        ),
        migrations.AddField(
            model_name='post',
            name='journey_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vehicleno',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vehicletype',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
