# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180407_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='f',
        ),
    ]
