# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('employeeID', models.CharField(max_length=250)),
                ('adharnumber', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanenumber', models.CharField(max_length=250)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employdetails')),
            ],
        ),
    ]
