# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOLLLOCATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
                ('numberoflanes', models.CharField(max_length=250)),
                ('numberofemployees', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='lane',
        ),
        migrations.DeleteModel(
            name='place',
        ),
    ]
