# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20180321_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolllocations',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employdetails'),
        ),
    ]
