# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_vehiclecharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecharges',
            name='monthlypass',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
